model:
  name: beetleResNet101
  pretrained: True
  num_classes: 8
  input_size: 224

train:
  batch_size: 32
  epochs: 500
  lr: 0.001
  optimizer: Adam
  augmentations:
    horizontal_flip: 0.5
    vertical_flip: 0.5
  save_every: 50
  mse_reduction: sum

test:
  batch_size: 1
  weights: best_model.pth
  mse_reduction: mean
  visualize: False

dataset:
  source_dir: path/to/indiviaual/images
  train:
    images: train
    labels: coords_train_val.csv
  val:
    images: val
    labels: coords_train_val.csv
  test:
    images: test
    labels: coords_test.csv